on:
  push:
  pull_request:

jobs:
  build:
    name: Run tests with pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-20.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install pytest
          #pip install -r ml_interfaces/bayesopt_interfaces/requirements.txt
      - name: Install bayesopt_interfaces
        run: |
          pip install ml_interfaces/bayesopt_interfaces
      - name: Run pytest
        run: pytest -v ml_interfaces/bayesopt_interfaces/tests/test_physbo_interface.py
